name: test
on:
  push:
    branches:
      - staging
      - prod
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - uses: namaggarwal/clasp-token-action@v0.0.1
        with:
          client-id: test-client-id
          client-secret: test-client-secret
          refresh-token: test-refresh-token
      - name: 'Install Requirements!'
        run: npm install
      # - name: 'Run Tests!'
      #   run: pytest -c app/tests/pytest.ini -m "not slow"




